services:
  cleanerrobot:
    image: cleanerrobot
    build:
      context: .
      dockerfile: CleanerRobot/Dockerfile
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: CleanerRobot
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data